import type { SceneId } from '../types';

export interface SceneAudioMeta {
  src: string;
  durationSec?: number;
  provider: string;
  requestId: string;
  model: string;
  voice: string;
  text: string;
}

// Auto-generated by scripts/generate-qwen-tts.mjs
export const SCENE_AUDIO: Partial<Record<SceneId, SceneAudioMeta>> = {
  "a": {
    "src": "tts/a/narration.wav",
    "durationSec": 6.908,
    "provider": "minimax",
    "requestId": "064f60e065e6881469a122f3f2c16c88",
    "model": "speech-2.8-hd",
    "voice": "moss_audio_aaa1346a-7ce7-11f0-8e61-2e6e3c7ee85d",
    "text": "Sam Altman 想必大家都不陌生,你以为他是ChatGPT之后才出名的？ 那就大错特错了"
  }
};
