import type { SceneId } from '../types';

export interface SceneAudioMeta {
  src: string;
  durationSec?: number;
  provider: string;
  requestId: string;
  model: string;
  voice: string;
  text: string;
}

// Auto-generated by scripts/generate-qwen-tts.mjs
export const SCENE_AUDIO: Partial<Record<SceneId, SceneAudioMeta>> = {
  "a": {
    "src": "tts/a/narration.wav",
    "durationSec": 9.683,
    "provider": "minimax",
    "requestId": "0650fd99b092c23bef21a5b24e5bdad5",
    "model": "speech-2.8-hd",
    "voice": "moss_audio_aaa1346a-7ce7-11f0-8e61-2e6e3c7ee85d",
    "text": "Sam Altman想必大家都不陌生。很多人都是通过 OpenAI 认识他的。但如果你以为他只是“ChatGPT 的老板”，那就太低估这个人了。"
  }
};
