import type { SceneId } from '../types';

export interface SceneAudioMeta {
  src: string;
  durationSec?: number;
  provider: string;
  requestId: string;
  model: string;
  voice: string;
  text: string;
}

// Auto-generated by scripts/generate-qwen-tts.mjs.
// Empty until the rebuilt s01-s25 script is rendered to fresh narration files.
export const SCENE_AUDIO: Partial<Record<SceneId, SceneAudioMeta>> = {};
